### ISSUE TITLE
Homework TODO

### ISSUE THREAD

**Issue by AVMiraga** [AVMiraga/DianaWeb#1]
# Homework TODO list
## Admin Panel CRUDs
- [x] "Category, Color, Material, Size" Models
- [x] Product and Image

## Views
- [x] Dynamic functionality for the landing page
- [x] Dynamic slider part
- [x] Dynamic footer (settings crud)

## Functionality
- [x] Identity Services to Project
- [x] Login Register Logic are done
- [ ] E-Mail subscription functionalty
